#!/usr/bin/bash

usage() {
    echo "Usage: $0 [--install <arg>]"
    echo "  --install <arg>   Install the application with argument <arg>"
    echo "Valid args:"
    echo "  python"
    echo "  node"
    echo "  golang"
    echo "  rust"
    echo "  vscode"
    echo "  all"
    exit 1
}

if [[ "$1" = "--help" ]]; then
    usage
elif [[ "$1" = "--install" ]]; then
    if [[ $# -gt 1 ]]; then
        INSTALL_ARG="$2"
    else
        echo "Error: --install requires an argument"
        usage
    fi
elif [[ -z "$1" ]]; then
    echo "Installing basic bash profile..."
    echo "Use --help to see all installation options"
else
    echo "Error: Unknown option: $1"
    usage
fi

root_dir=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")

source "${root_dir}/install/bash.sh"

if [[ "${INSTALL_ARG}" = "all" || "${INSTALL_ARG}" = "python" ]]; then
    source "${root_dir}/install/python.sh"
fi

if [[ "${INSTALL_ARG}" = "all" || "${INSTALL_ARG}" = "node" ]]; then
    source "${root_dir}/install/node.sh"
fi

if [[ "${INSTALL_ARG}" = "all" || "${INSTALL_ARG}" = "golang" ]]; then
    source "${root_dir}/install/golang.sh"
fi

if [[ "${INSTALL_ARG}" = "all" || "${INSTALL_ARG}" = "rust" ]]; then
    source "${root_dir}/install/rust.sh"
fi

if [[ "${INSTALL_ARG}" = "all" || "${INSTALL_ARG}" = "vscode" ]]; then
    source "${root_dir}/.vscode/vsc_extensions.sh"
fi

source ~/.bashrc

echo "dotfiles setup complete!"
