#! /bin/bash
# Open any file in ~/projects from anywhere

cdp() {
    folder="$1"
    projects_dir="${HOME}/projects"

    if [ -d "${projects_dir}/${folder}" ]; then
        cd "${projects_dir}/${folder}"
    else
        echo "Directory '${folder}' not found in ${projects_dir}"
    fi
}
